# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Mantle-UI Node CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          
      - name: Test the library
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test` command

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write "**/*.(js|jsx|ts|tsx|css|html|md)"
